export interface Plantas{
    IDPlanta: string,
    NombrePlanta: string,
    Temporada: string,
    DiasFertilizacion: number,
    DiasGerminacion: number,
    DiasTransplante: number,
    DiasCrecVegetativo: number,
    DiasCrecInflorecencia: number,
    DiasFruto: number,
    DiasCosecha: number,
    TipoLuz: string,
    DiasRiego: number,
    TempMin: string,
    TempMax: string,
    DistTransplanteCm: number,
    Recomendaciones: string,
    Descripcion: string,
    NombreCientifico: string,
    TipoSiembra: string,
    MonitoreoPLagas: number,
    FotoPlanta: string
}